### ISSUE TITLE
Connect the navigation bar to their respective layout.

### ISSUE THREAD

**Issue by ayushman999** [hackslash-nitp/habita-android#22]
Right now, only the transition of the navigation bar is working. Your work will be to assign each option in the navigation bar to their respective layout screen. The dependency of the navigation bar used in this project is [https://github.com/ismaeldivita/chip-navigation-bar](url). You can go through this and know how this navigation bar is working.

**Comment by abdulbasit75** [comment]
I would like to work on this, please assign me.

**Comment by ayushman999** [comment]
Sorry, but it's already assigned to one member.
